services:
  db:
    image: postgres:16
    container_name: db_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: app_container
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      CAMUNDA_CLIENT_GRPCADDRESS: http://host.docker.internal:26500
      CAMUNDA_CLIENT_RESTADDRESS: http://host.docker.internal:8080
    ports:
      - "8081:8081"

volumes:
  db_data: